### ISSUE TITLE
Session/Daily cash doesn't work

### ISSUE THREAD

**Issue by spawn900** [homeopatix/AltHolic#4]
The cash window doesn't display the session or daily cash. Therefor it can't display the total amount of money. I tried every option to enable it, but it doesn't work.
Of course I played with all of the chars the proto-dailies, so they had earned some money.

![ScreenShot_2024-02-26_191850_0](https://github.com/homeopatix/AltHolic/assets/9595947/0830d61d-9b94-40c7-b5e4-cb9138306a4c)

**Comment by homeopatix** [comment]
I will check that asap

thank you for the feed back

Homeo
